name: Build

on:
  push:
    branches: ['*'] # Run on any pushed branch, but not on any pushed tag
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    if: github.event_name != 'pull_request' || 1 == 1
    strategy:
      matrix:
        os: ['ubuntu-22.04', 'macos-12' ] # 'windows-latest' too flaky
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: 'Set up Java'
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0
        with:
          java-version: 17
          distribution: 'temurin'

      - name: 'Cache Maven packages'
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.target') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test
        uses: coactions/setup-xvfb@b6b4fcfb9f5a895edadc3bc76318fae0ac17c8b3
        with: 
          run: ./mvnw clean verify -PuseJenkinsSnapshots -f org.eclipse.xtext.full.releng

  build-maven-artifacts:
    if: github.event_name != 'pull_request' || 1 == 1
    runs-on: ubuntu-22.04

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: 'Set up Java'
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0
        with:
          java-version: 17
          distribution: 'temurin'

      - name: 'Cache Maven packages'
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml', '**/*.target') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build Maven artifacts
        run: ./mvnw clean verify -PuseJenkinsSnapshots -f org.eclipse.xtext.maven.releng
